version: '3.8'

services:
  event-collector:
    container_name: event-collector-prod
    env_file:
      - database_local.env
      - .env
    environment:
      - NODE_ENV=STAGING
    build:
      dockerfile: Dockerfile.staging
      context: "./backend/event-collector"
    volumes:
      - /app/node_modules
      - ./backend/event-collector:/app
    ports:
      - '3000:3000'
  
  query-collector:
    container_name: query-service-prod
    env_file:
      - database_local.env
      - .env
    build:
      dockerfile: Dockerfile.staging
      context: "./backend/query-service"
    environment:
      - NODE_ENV=STAGING
    volumes:
      - /app/node_modules
      - ./backend/query-service:/app
    ports:
      - '6060:6060'

  fusion-app:
    container_name: frontend-prod
    build:
      context: ./frontend
      dockerfile: Dockerfile.staging
    env_file:
      - .env
    environment:
      - NODE_ENV=STAGING
    volumes:
      - /app/node_modules
      - ./frontend:/app
    ports:
      - '4040:4040'

  database:
    image: "postgres" # use latest official postgres version
    ports:
      - "5432:5432"
    env_file:
      - database_local.env # configure postgres
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down

volumes:
  database-data: # named volumes can be managed easier using docker-compose